version: '3'
services:
  api:
    build: .
    container_name: basic-api-docker
    ports:
      - 5000:5000
    volumes:
      - ./tokens.json:/app/tokens.json
      - /var/run/docker.sock:/var/run/docker.sock